# Change these first
owner: alice-e-still # Your GitHub organization or username, where this repository lives
repo: boldlight-upptime-test # The name of this repository

sites:
 
  - name: Altyn Dala
    url: https://altyndala.org
    maxResponseTime: 300000
  - name: ARUK
    url: https://www.alzheimersresearchuk.org
    maxResponseTime: 300000
  - name: Back from the Brink
    url: https://naturebftb.co.uk
    maxResponseTime: 300000
  - name: Dynamic Dunescapes
    url: https://dynamicdunescapes.co.uk
    maxResponseTime: 300000
  - name: Farm Wildlife
    url: https://farmwildlife.info
    maxResponseTime: 300000
  - name: KRUK
    url: https://kidneyresearchuk.org
    maxResponseTime: 300000
  - name: Little Tern Project
    url: https://littleternproject.org.uk
    maxResponseTime: 300000
  - name: After Minerals
    url: https://afterminerals.com
    maxResponseTime: 300000
  - name: Project Godwit
    url: https://projectgodwit.org.uk
    maxResponseTime: 300000
  - name: Save Our Seabed
    url: https://saveourseabed.co.uk
    maxResponseTime: 300000
  - name: RSPB BAI Hub
    url: https://baihub.rspb.org.uk
    maxResponseTime: 300000
  - name: Save Vultures
    url: https://save-vultures.org
    maxResponseTime: 300000
  - name: Rethink Nature
    url: https://rethinknature.co.uk
    maxResponseTime: 300000
  - name: Upper & Bedford Ouse Catchment Partnership
    url: https://ubocp.org.uk
    maxResponseTime: 300000
  - name: Visit Sherwood
    url: https://visitsherwood.co.uk
    maxResponseTime: 300000
  - name: RSPB Wild Challence
    url: https://wildchallenge.rspb.org.uk
    maxResponseTime: 300000
  - name: For Baby's Sake
    url: https://forbabyssake.org.uk
    maxResponseTime: 300000
  - name: Cats Protection Audiences
    url: https://audiences.cats.org.uk
    maxResponseTime: 300000
  - name: Parkrun (Donate)
    url: https://donate.parkrun.com
    maxResponseTime: 300000
  - name: Nurture BioBank
    url: https://nurturebiobank.org
    maxResponseTime: 300000
  - name: WDC
    url: https://whales.org
    maxResponseTime: 300000
  - name: Edon Initiative
    url: https://edon-initiative.org
    maxResponseTime: 300000
  - name: Curlew Life
    url: https://curlewlife.org
    maxResponseTime: 300000
  - name: Restore BCR
    url: https://restore-bcr.co.uk
    maxResponseTime: 300000
  - name: Atlantic Guardians
    url: https://atlanticguardians.org
    maxResponseTime: 300000
  - name: MAGPAS
    url: https://magpas.org.uk
    maxResponseTime: 300000
  - name: NerdFest
    url: https://nerdfest.org.uk
    maxResponseTime: 300000
  - name: Ring Ouzel
    url: https://ringouzel.info
    maxResponseTime: 300000
  - name: Ethiopiaid (UK)
    url: https://ethiopiaid.org.uk
    maxResponseTime: 300000
  - name: Ethiopiaid (Ireland)
    url: https://ethiopiaid.ie
    maxResponseTime: 300000
  - name: RSPB Groups
    url: https://group.rspb.org.uk/bedford/
    maxResponseTime: 300000
  - name: Boldlight Site
    url: https://boldlight.co.uk
    maxResponseTime: 300000
  - name: Boldlight Studio
    url: https://boldlight.studio
    maxResponseTime: 300000
  - name: Boldlight Team
    url: https://boldlight.team
    maxResponseTime: 300000
  - name: Boldlight Wiki
    url: https://boldlight.wiki
    maxResponseTime: 300000
  - name: Smyth Accountants
    url: https://smythaccountants.co.uk
    maxResponseTime: 300000
  - name: Sky Badger
    url: https://skybadger.co.uk
    maxResponseTime: 300000
delay: 1000
assignees:
  - alice-e-still 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /boldlight-upptime-test
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Boldlight Upptime Test
  introTitle: Boldlight Upptime Test 
  introMessage: Monitoring the status of Boldlight Services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/20 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
