# Change these first
owner: alice-e-still # Your GitHub organization or username, where this repository lives
repo: boldlight-upptime-test # The name of this repository

sites:
  - name: WDC Intermediary Database Interface
    url: https://wdc-interface.uksouth.cloudapp.azure.com/wdc_idb_live/
    check: "tcp-ping"
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Boldlight Upptime test
  introTitle: Boldlight Upptime Test
  introMessage: Testing
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
